### ISSUE TITLE
Avoid using Pkg internals

### ISSUE THREAD

**Issue by ericphanson** [SamuraiAku/PkgToSoftwareBOM.jl#15]
functions like https://github.com/SamuraiAku/PkgToSoftwareBOM.jl/blob/938168a775658ebcd173e1e1cb45471e05c48105/src/packageInfo.jl#L3 are using Pkg internals, which have changed in the past.

One tool that can help is https://github.com/GunnarFarneback/RegistryInstances.jl which provides a public API for the RegistryInstances portion of what Pkg does. (See the `Background` section of the README there).

**Comment by SamuraiAku** [comment]
This package has no releases yet, but this is the functionality I am looking for. I’ll keep an eye on this. Thanks for the tip.

**Comment by ericphanson** [comment]
RegistryInstances actually does have a registered release in General: https://github.com/JuliaRegistries/General/blob/master/R/RegistryInstances/Package.toml. It doesn't have TagBot setup (fyi @GunnarFarneback), which is why nothing shows up as a github release. (I know since I'm [using it in PackageAnalyzer.jl](https://github.com/JuliaEcosystem/PackageAnalyzer.jl/blob/11d0d26d641c7478f3d4b4e7c6520d2b05c1bba3/Project.toml#L18)).
