### ISSUE TITLE
Add PkgToSoftwareBOM.jl to SPDX's list of OSS tools

### ISSUE THREAD

**Issue by hannahilea** [SamuraiAku/PkgToSoftwareBOM.jl#16]
...which is here: https://spdx.dev/tools-community/

**Comment by SamuraiAku** [comment]
Submitted an announcement to the spdx-outreach list.

**Comment by nsajko** [comment]
It seems that, to add PkgToSoftwareBOM.jl to https://spdx.dev/use/tools/open-source-tools/, it's necessary to create an issue here: https://github.com/spdx/outreach

There's also this list: https://cyclonedx.org/tool-center/. It seems PRs are accepted here: https://github.com/CycloneDX/cyclonedx.org

**Comment by SamuraiAku** [comment]
Finally added to the list

https://spdx.dev/use/spdx-tools
