### ISSUE TITLE
Fill in Declared License field in SBOM

### ISSUE THREAD

**Issue by SamuraiAku** [SamuraiAku/PkgToSoftwareBOM.jl#7]
Includes declared license and package summary.  That costs a user with each query and requires a Github login?  Need to research that. Include flags to not use the API and to tell the user how many API actions an SBOM would cost them without actually doing it.

**Comment by SamuraiAku** [comment]
Does LicenseCheck.jl require the user to install Go themselves?  I want to make this package accessible to the entire Julia community and I don't think a requirement like that is going to work.

No need to download code. PkgToSoftwareBOM only work on an active environment which means all the code was already downloaded by Pkg.

**Comment by ericphanson** [comment]
LicenseCheck uses a JLL, and PackageAnalyzer will reuse the code downloaded by Pkg if it is available.

**Comment by SamuraiAku** [comment]
@ericphanson I have a pull request in LicenseCheck.jl that will allow it to scan sub-directories.  I could implement the directory scanning within PkgToSoftwareBOM but I think it's cleaner implemented within the package. Do you think there's a possibility of this being merged and released in the near future? Thanks.
